DROP TABLE IF EXISTS TRANSLATION;
CREATE TABLE TRANSLATION
(
    id     BIGINT AUTO_INCREMENT PRIMARY KEY,
    number INT          NOT NULL,
    french VARCHAR(255) NOT NULL,
    german VARCHAR(255) NOT NULL
);